# Generated by Django 2.1.5 on 2019-03-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ivents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivent_id', models.PositiveIntegerField(default=0)),
                ('date_times', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(height_field=171, upload_to='', width_field=320)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('picture', models.ImageField(height_field=128, upload_to='', width_field=128)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.PositiveIntegerField(default=0)),
                ('order_id', models.PositiveIntegerField(default=0)),
                ('row', models.PositiveIntegerField(default=0)),
                ('number', models.PositiveIntegerField(default=0)),
                ('ivent_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concert.Ivents')),
                ('ovner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concert.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.PositiveIntegerField(default=0)),
                ('venue_title', models.CharField(max_length=50)),
                ('venue_adress', models.CharField(max_length=150)),
                ('region', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ivents',
            name='venue_id',
            field=models.ManyToManyField(to='concert.Venue'),
        ),
        migrations.AddField(
            model_name='artist',
            name='Ivents',
            field=models.ManyToManyField(to='concert.Ivents'),
        ),
    ]
