# Generated by Django 2.1.5 on 2019-03-23 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concert.Artist')),
            ],
        ),
    ]
