# Generated by Django 2.1.5 on 2019-03-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_auto_20190323_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concert.Artist')),
                ('ovner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concert.Person')),
            ],
        ),
    ]
